# ansible-playbook playbookNameFile.yml -i InventoryName
- name: installation httpd (Apache)
  # use packages until yum
  yum:
    name: httpd
    state: latest

- name: pre-copy index.html
  debug:
    msg: 'COPY index.html'

- name: copy files/html to var/www/html
  copy: 
    src: index.html
    dest: /var/www/html/index.html

- name: restart httpd
  shell: systemctl restart httpd

- name: virtualhost
  template: 
    src: virtualHost.conf.j2 
    dest: /etc/httpd/conf.d/virtual.conf

- name: Remplace port 81 par 8081 
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen 81'
    line: Listen 8081