---
#
#
# docker-compose up --build
#
version: '3.8'

services:
  jenkins:
    build:
      context: .
    ports:
      - 81:8081 #mon port 80 est déjà pris par autre chose en permanence
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./conf:/var/jenkins_config/
      - ./ansible-files/:/ansible-files/
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_config/jenkins.yaml
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin
      - JENKINS_OPTS="--httpPort=8081"
volumes:
  jenkins_home: