- name: use apache_vhost role playbook
  hosts: terraform
  become: true

  pre_tasks:
    - debug:
        msg: 'Beginning web server configuration.'

  roles:
    - apache

  post_tasks:
    - debug:
        msg: 'Web server has been configured.'